[activemq.cpv_0]
path = "repo/src/main/java/org/apache/activemq/openwire/v1/BaseDataStreamMarshaller.java"
line = 234
class_name = "org.apache.activemq.openwire.v1.BaseDataStreamMarshaller"
harness = ["ActivemqOne", "ActivemqOneFDP"]

[batik.cpv_0]
path = "repo/src/main/java/org/apache/batik/util/ParsedURLData.java"
line = 554
class_name = "org.apache.batik.util.ParsedURLData"
harness = ["BatikOne", "BatikOneFDP"]

[bcel.cpv_0]
path = "repo/src/main/java/org/apache/bcel/verifier/statics/Pass2Verifier.java"
line = 973
class_name = "org.apache.bcel.verifier.statics.Pass2Verifier$CPESSC_Visitor"
harness = ["BCELOne", "BCELOneFDP"]

[beanutils.cpv_0]
path = "repo/src/main/java/com/aixcc/beanutils/harnesses/one/BeanUtilsOne.java"
line = 79
class_name = "com.aixcc.beanutils.harnesses.one.BeanUtilsOne"
harness = "BeanUtilsOne"

[cron-utils.cpv_0]
path = "repo/src/main/java/com/aixcc/cronutils/harnesses/one/CronUtilsOne.java"
line = 35
class_name = "com.aixcc.cronutils.harnesses.one.CronUtilsOne"
harness = ["CronUtilsOne", "CronUtilsOneFDP"]

[cxf.cpv_0]
path = "repo/src/main/java/com/aixcc/cxf/harnesses/one/CXFOne.java"
line = 35
class_name = "com.aixcc.cxf.harnesses.one.CXFOne"
harness = "CXFOne"

[cxf.cpv_1]
path = "repo/src/main/java/com/aixcc/cxf/harnesses/two/CXFTwo.java"
line = 36
class_name = "com.aixcc.cxf.harnesses.two.CXFTwo"
harness = "CXFTwo"

[cxf.cpv_2]
path = "repo/src/main/java/org/apache/cxf/jaxrs/utils/ResourceUtils.java"
line = 577
class_name = "org.apache.cxf.jaxrs.utils.ResourceUtils"
harness = ["CXFThree", "CXFThreeFDP"]

[feign.cpv_2]
path = "repo/src/main/java/feign/template/Expression.java"
line = 35
class_name = "feign.template.Expression"
harness = "BodyTemplateFuzzer"

[fuzzy.cpv_0]
path = "repo/src/main/java/me/xdrop/fuzzywuzzy/Config.java"
line = 84
class_name = "me.xdrop.fuzzywuzzy.Config"
harness = ["FuzzyOne", "FuzzyOneFDP"]

[geonetwork.cpv_0]
path = "repo/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java"
line = 242
class_name = "org.fao.geonet.kernel.harvest.harvester.localfilesystem.LocalFilesystemHarvester"
harness = ["GeonetworkOne", "GeonetworkOneFDP"]

[htmlunit.cpv_0]
path = "repo/src/main/java/org/htmlunit/javascript/host/xml/XSLTProcessor.java"
line = 262
class_name = "org.htmlunit.javascript.host.xml.XSLTProcessor"
harness = ["HtmlunitOne", "HtmlunitOneFDP"]

[imaging.cpv_0]
path = "repo/src/main/java/org/apache/commons/imaging/formats/png/chunks/PngChunkZtxt.java"
line = 62
class_name = "org.apache.commons.imaging.formats.png.chunks.PngChunkZtxt"
harness = ["ImagingOne", "ImagingOneFDP"]

[imaging.cpv_1]
path = "repo/src/main/java/org/apache/commons/imaging/formats/gif/ApplicationExtension.java"
line = 34
class_name = "org.apache.commons.imaging.formats.gif.ApplicationExtension"
harness = ["ImagingOne", "ImagingOneFDP"]

[imaging.cpv_2]
path = "repo/src/main/java/org/apache/commons/imaging/formats/jpeg/segments/PatSegment.java"
line = 93
class_name = "org.apache.commons.imaging.formats.jpeg.segments.PatSegment"
harness = ["ImagingTwo", "ImagingTwoFDP"]

[jackson-databind.cpv_0]
path = "repo/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotatedConstructor.java"
line = 129
class_name = "com.fasterxml.jackson.databind.introspect.AnnotatedConstructor"
harness = ["JacksonDatabindOne", "JacksonDatabindOneFDP"]

[jakarta-mail-api.cpv_0]
path = "repo/src/main/java/org/eclipse/angus/mail/handlers/text_xml.java"
line = 95
class_name = "org.eclipse.angus.mail.handlers.text_xml"
harness = ["MailApiHarnessOne", "MailApiHarnessOneFDP"]

[jenkins.cpv_0]
path = "repo/src/main/java/io/jenkins/plugins/UtilPlug/UtilMain.java"
line = 194
class_name = "io.jenkins.plugins.UtilPlug.UtilMain"
harness = ["JenkinsTwo", "JenkinsTwoFDP"]

[jenkins.cpv_1]
path = "repo/src/main/java/io/jenkins/plugins/toyplugin/Script.java"
line = 84
class_name = "io.jenkins.plugins.toyplugin.Script"
harness = ["JenkinsThree", "JenkinsThreeFDP"]

[jenkins.cpv_10]
path = "repo/src/main/java/io/jenkins/plugins/toyplugin/SecretMessage.java"
line = 98
class_name = "io.jenkins.plugins.toyplugin.SecretMessage"
harness = ["JenkinsThree", "JenkinsThreeFDP"]

[jenkins.cpv_11]
path = "repo/src/main/java/io/jenkins/plugins/toyplugin/AccessFilter.java"
line = 87
class_name = "io.jenkins.plugins.toyplugin.AccessFilter"
harness = ["JenkinsThree", "JenkinsThreeFDP"]

[jenkins.cpv_12]
path = "repo/src/main/java/com/sonyericsson/jenkins/plugins/bfa/CauseManagement.java"
line = 245
class_name = "com.sonyericsson.jenkins.plugins.bfa.CauseManagement"
harness = ["JenkinsFour", "JenkinsFourFDP"]

[jenkins.cpv_13]
path = "repo/src/main/java/com/sonyericsson/jenkins/plugins/bfa/db/LocalFileKnowledgeBase.java"
line = 130
class_name = "com.sonyericsson.jenkins.plugins.bfa.db.LocalFileKnowledgeBase"
harness = ["JenkinsFour", "JenkinsFourFDP"]

[jenkins.cpv_14]
path = "repo/src/main/java/hudson/plugins/emailext/EmailConfig.java"
line = 102
class_name = "hudson.plugins.emailext.EmailConfig"
harness = ["JenkinsFive", "JenkinsFiveFDP"]

[jenkins.cpv_2]
path = "repo/src/main/java/hudson/PluginManager.java"
line = 1640
class_name = "hudson.PluginManager"
harness = ["JenkinsThree", "JenkinsThreeFDP"]

[jenkins.cpv_3]
path = "repo/src/main/java/hudson/ProxyConfiguration.java"
line = 593
class_name = "hudson.ProxyConfiguration$DescriptorImpl2"
harness = ["JenkinsThree", "JenkinsThreeFDP"]

[jenkins.cpv_4]
path = "repo/src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java"
line = 733
class_name = "io.jenkins.plugins.coverage.CoverageProcessor"
harness = ["JenkinsThree", "JenkinsThreeFDP"]

[jenkins.cpv_5]
path = "repo/src/main/java/io/jenkins/plugins/toyplugin/UserNameAction.java"
line = 74
class_name = "io.jenkins.plugins.toyplugin.UserNameAction"
harness = ["JenkinsThree", "JenkinsThreeFDP"]

[jenkins.cpv_6]
path = "repo/src/main/java/io/jenkins/plugins/toyplugin/StateMonitor.java"
line = 58
class_name = "io.jenkins.plugins.toyplugin.StateMonitor"
harness = ["JenkinsThree", "JenkinsThreeFDP"]

[jenkins.cpv_7]
path = "repo/src/main/java/hudson/Proc.java"
line = 252
class_name = "hudson.Proc$LocalProc"
harness = ["JenkinsThree", "JenkinsThreeFDP"]

[jenkins.cpv_8]
path = "repo/src/main/java/io/jenkins/plugins/toyplugin/AuthAction.java"
line = 229
class_name = "io.jenkins.plugins.toyplugin.AuthAction"
harness = ["JenkinsThree", "JenkinsThreeFDP"]

[jenkins.cpv_9]
path = "repo/src/main/java/jenkins/util/xml/XMLUtils.java"
line = 236
class_name = "jenkins.util.xml.XMLUtils"
harness = ["JenkinsThree", "JenkinsThreeFDP"]

[kylin.cpv_0]
path = "repo/src/main/java/org/apache/kylin/common/util/CliCommandExecutor.java"
line = 126
class_name = "org.apache.kylin.common.util.CliCommandExecutor"
harness = ["KylinOne", "KylinOneFDP"]

[netty.cpv_1]
path = "repo/src/main/java//HttpRequestDecoder.java"
line = 265
class_name = "HttpRequestDecoder"
harness = "HttpRequestDecoderFuzzer"

[olingo.cpv_0]
path = "repo/src/main/java/org/apache/olingo/client/core/communication/request/v4/AsyncRequestWrapperImpl.java"
line = 303
class_name = "org.apache.olingo.client.core.communication.request.v4.AsyncRequestWrapperImpl"
harness = ["OlingoOne", "OlingoOneFDP"]

[oripa.cpv_0]
path = "repo/src/main/java/oripa/persistence/doc/loader/LoaderXML.java"
line = 44
class_name = "oripa.persistence.doc.loader.LoaderXML"
harness = ["OripaOne", "OripaOneFDP"]

[pac4j.cpv_0]
path = "repo/src/main/java/org/pac4j/core/util/JavaSerializationHelper.java"
line = 82
class_name = "org.pac4j.core.util.JavaSerializationHelper"
harness = ["Pac4jOne", "Pac4jOneFDP"]

[r1-zookeeper.cpv_2]
path = "repo/src/main/java/org/apache/zookeeper/server/DataTree.java"
line = 2178
class_name = "org.apache.zookeeper.server.DataTree"
harness = "DataTreeFuzzer"

[r1-zookeeper.cpv_3]
path = "repo/src/main/java/org/apache/zookeeper/server/DataTree.java"
line = 1077
class_name = "org.apache.zookeeper.server.DataTree"
harness = "MultiProcessTxnFuzzer"

[r1-zookeeper.cpv_4]
path = "repo/src/main/java/org/apache/zookeeper/server/DataTree.java"
line = 2182
class_name = "org.apache.zookeeper.server.DataTree"
harness = "MultiProcessTxnFuzzer"

[r2-apache-commons-compress.cpv_0]
path = "repo/src/main/java/org/apache/commons/compress/archivers/zip/ZipFile.java"
line = 1552
class_name = "org.apache.commons.compress.archivers.zip.ZipFile"
harness = "CompressZipFuzzer"

[r2-apache-commons-compress.cpv_1]
path = "repo/src/main/java/org/apache/commons/compress/compressors/gzip/GzipCompressorInputStream.java"
line = 399
class_name = "org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream"
harness = "CompressorGzipFuzzer"

[r2-apache-commons-compress.cpv_2]
path = "repo/src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveEntry.java"
line = 1559
class_name = "org.apache.commons.compress.archivers.tar.TarArchiveEntry"
harness = "CompressTarFuzzer"

[r2-apache-commons-compress.cpv_3]
path = "repo/src/main/java/org/apache/commons/compress/archivers/examples/Expander.java"
line = 86
class_name = "org.apache.commons.compress.archivers.examples.Expander"
harness = "ExpanderFuzzer"

[r2-zookeeper.cpv_0]
path = "repo/src/main/java/org/apache/zookeeper/server/DataTree.java"
line = 555
class_name = "org.apache.zookeeper.server.DataTree"
harness = "MultiProcessTxnFuzzer"

[r3-tika-delta-01.cpv_0]
path = "repo/src/main/java/org/apache/tika/parser/external/ExternalParser.java"
line = 314
class_name = "org.apache.tika.parser.external.ExternalParser"
harness = "HtmlParserFuzzer"

[r3-tika-delta-02.cpv_0]
path = "repo/src/main/java/org/apache/tika/io/TikaInputStream.java"
line = 606
class_name = "org.apache.tika.io.TikaInputStream"
harness = "M3U8ParserFuzzer"

[r3-tika-delta-03.cpv_0]
path = "repo/src/main/java/org/apache/tika/parser/threedxml/ThreeDXMLParser.java"
line = 141
class_name = "org.apache.tika.parser.threedxml.ThreeDXMLParser"
harness = "ThreeDXMLParserFuzzer"

[r3-tika-delta-04.cpv_0]
path = "repo/src/main/java/org/apache/tika/pipes/emitter/fs/FileSystemEmitter.java"
line = 155
class_name = "org.apache.tika.pipes.emitter.fs.FileSystemEmitter"
harness = "TikaAppRUnpackerFuzzer"

[r3-tika-delta-05.cpv_0]
path = "repo/src/main/java/org/apache/tika/cli/TikaCLI.java"
line = 1111
class_name = "org.apache.tika.cli.TikaCLI$FileEmbeddedDocumentExtractor"
harness = "TikaAppUnpackerFuzzer"

[r3-tika.cpv_0]
path = "repo/src/main/java/org/apache/tika/parser/xliff/XLIFF12Parser.java"
line = 88
class_name = "org.apache.tika.parser.xliff.XLIFF12Parser"
harness = "XliffParserFuzzer"

[r3-tika.cpv_1]
path = "repo/src/main/java/org/apache/tika/parser/microsoft/rtf/RTFEmbObjHandler.java"
line = 217
class_name = "org.apache.tika.parser.microsoft.rtf.RTFEmbObjHandler"
harness = "RTFParserFuzzer"

[r3-tika.cpv_2]
path = "repo/src/main/java/org/apache/tika/cli/TikaUntar.java"
line = 47
class_name = "org.apache.tika.cli.TikaUntar"
harness = "TikaAppUntarringFuzzer"

[r3-tika.cpv_3]
path = "repo/src/main/java/org/apache/tika/parser/csv/TextAndCSVParser.java"
line = 278
class_name = "org.apache.tika.parser.csv.TextAndCSVParser"
harness = "TextAndCSVParserFuzzer"

[r3-tika.cpv_4]
path = "repo/src/main/java/org/apache/tika/utils/ProcessUtils.java"
line = 94
class_name = "org.apache.tika.utils.ProcessUtils"
harness = "TikaAppUnpackerFuzzer"

[r3_5-jackson-databind.cpv_0]
path = "repo/src/main/java/com/fasterxml/jackson/databind/ser/BeanPropertyWriter.java"
line = 688
class_name = "com.fasterxml.jackson.databind.ser.BeanPropertyWriter"
harness = "AdaLObjectReader3Fuzzer"

[rdf4j.cpv_0]
path = "repo/src/main/java/org/eclipse/rdf4j/common/xml/SimpleSAXParser.java"
line = 221
class_name = "org.eclipse.rdf4j.common.xml.SimpleSAXParser"
harness = ["Rdf4jOne", "Rdf4jOneFDP"]

[rdf4j.cpv_1]
path = "repo/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParser.java"
line = 328
class_name = "org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser"
harness = ["Rdf4jOne", "Rdf4jOneFDP"]

[rdf4j.cpv_2]
path = "repo/src/main/java/org/eclipse/rdf4j/common/io/IOUtil.java"
line = 387
class_name = "org.eclipse.rdf4j.common.io.IOUtil"
harness = ["Rdf4jOne", "Rdf4jOneFDP"]

[shiro.cpv_0]
path = "repo/src/main/java/org/apache/shiro/io/DefaultSerializer.java"
line = 77
class_name = "org.apache.shiro.io.DefaultSerializer"
harness = "ShiroOne"

[struts.cpv_0]
path = "repo/src/main/java/org/apache/tiles/el/ELAttributeEvaluator.java"
line = 90
class_name = "org.apache.tiles.el.ELAttributeEvaluator"
harness = "StrutsOne"

[tika.cpv_0]
path = "repo/src/main/java/org/apache/tika/cli/TikaCLI.java"
line = 1103
class_name = "org.apache.tika.cli.TikaCLI$FileEmbeddedDocumentExtractor"
harness = ["TikaOne", "TikaOneFDP"]

[tika.cpv_1]
path = "repo/src/main/java/org/apache/tika/parser/external/ExternalParser.java"
line = 161
class_name = "org.apache.tika.parser.external.ExternalParser"
harness = ["TikaTwo", "TikaTwoFDP"]

[widoco.cpv_0]
path = "repo/src/main/java/widoco/WidocoUtils.java"
line = 269
class_name = "widoco.WidocoUtils"
harness = ["WidocoOne", "WidocoOneFDP"]

[xstream.cpv_2]
path = "repo/src/main/java/com/thoughtworks/xstream/io/xml/DomDriver.java"
line = 108
class_name = "com.thoughtworks.xstream.io.xml.DomDriver"
harness = "XmlFuzzer"

[xstream.cpv_4]
path = "repo/src/main/java/com/thoughtworks/xstream/converters/extended/StringInterpolationConverter.java"
line = 195
class_name = "com.thoughtworks.xstream.converters.extended.StringInterpolationConverter"
harness = "XmlFuzzer"

[ztzip.cpv_0]
path = "repo/src/main/java/org/zeroturnaround/zip/commons/FileUtils.java"
line = 54
class_name = "org.zeroturnaround.zip.commons.FileUtils"
harness = ["ZTZIPOne", "ZTZIPOneFDP"]

