python3 misc/eva/analyze.py aixcc/jvm/activemq
#python3 misc/eva/analyze.py aixcc/jvm/activemq-var
python3 misc/eva/analyze.py aixcc/jvm/batik
python3 misc/eva/analyze.py aixcc/jvm/bcel
python3 misc/eva/analyze.py aixcc/jvm/beanutils
python3 misc/eva/analyze.py aixcc/jvm/cron-utils
python3 misc/eva/analyze.py aixcc/jvm/cxf
python3 misc/eva/analyze.py aixcc/jvm/feign
python3 misc/eva/analyze.py aixcc/jvm/fuzzy
python3 misc/eva/analyze.py aixcc/jvm/geonetwork
python3 misc/eva/analyze.py aixcc/jvm/htmlunit
python3 misc/eva/analyze.py aixcc/jvm/imaging
python3 misc/eva/analyze.py aixcc/jvm/jackson-databind
python3 misc/eva/analyze.py aixcc/jvm/jakarta-mail-api
python3 misc/eva/analyze.py aixcc/jvm/jenkins
python3 misc/eva/analyze.py aixcc/jvm/kylin
python3 misc/eva/analyze.py aixcc/jvm/netty
python3 misc/eva/analyze.py aixcc/jvm/olingo
python3 misc/eva/analyze.py aixcc/jvm/oripa
python3 misc/eva/analyze.py aixcc/jvm/pac4j
python3 misc/eva/analyze.py aixcc/jvm/r1-zookeeper
python3 misc/eva/analyze.py aixcc/jvm/r2-apache-commons-compress
python3 misc/eva/analyze.py aixcc/jvm/r2-zookeeper
python3 misc/eva/analyze.py aixcc/jvm/r3_5-jackson-databind
python3 misc/eva/analyze.py aixcc/jvm/r3-tika
python3 misc/eva/analyze.py aixcc/jvm/r3-tika-delta-01
python3 misc/eva/analyze.py aixcc/jvm/r3-tika-delta-02
python3 misc/eva/analyze.py aixcc/jvm/r3-tika-delta-03
python3 misc/eva/analyze.py aixcc/jvm/r3-tika-delta-04
python3 misc/eva/analyze.py aixcc/jvm/r3-tika-delta-05
python3 misc/eva/analyze.py aixcc/jvm/rdf4j
python3 misc/eva/analyze.py aixcc/jvm/shiro
python3 misc/eva/analyze.py aixcc/jvm/struts
python3 misc/eva/analyze.py aixcc/jvm/tika
python3 misc/eva/analyze.py aixcc/jvm/widoco
python3 misc/eva/analyze.py aixcc/jvm/xstream
python3 misc/eva/analyze.py aixcc/jvm/ztzip
