#bash dev.sh test aixcc/jvm/mock-java '*' 600 true
##bash dev.sh test aixcc/jvm/mock-java '*' 3600 false
#bash dev.sh test  aixcc/jvm/r3-zookeeper-delta-02 'MultiProcessTxnFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/r3-apache-commons-compress 'CompressTarFuzzer' 7200 true
#bash dev.sh test aixcc/jvm/r2-apache-commons-compress 'CompressTarFuzzer,CompressZipFuzzer,CompressorGzipFuzzer,ExpanderFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/r2-apache-commons-compress 'CompressorBZip2Fuzzer,CompressTarFuzzer,CompressZipFuzzer,CompressorGzipFuzzer,ExpanderFuzzer' 3600 false
#bash dev.sh test aixcc/jvm/r2-apache-commons-compress-diff-1 'CompressTarFuzzer,CompressZipFuzzer,CompressorGzipFuzzer,ExpanderFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/r2-apache-commons-compress-diff-2 'CompressTarFuzzer,CompressZipFuzzer,CompressorGzipFuzzer,ExpanderFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/r2-zookeeper 'MultiProcessTxnFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/r2-zookeeper-diff-1 'MessageTrackerPeekReceivedFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/jenkins 'JenkinsTwo|JenkinsThree|JenkinsFour|JenkinsFive' 3600 true
#bash dev.sh test aixcc/jvm/imaging 'ImagingOne,ImagingTwo' 3600 true
#bash dev.sh test aixcc/jvm/imaging 'ImagingTwo' 600 true
#bash dev.sh test aixcc/jvm/geonetwork '*' 3600 true
#bash dev.sh test aixcc/jvm/batik '*' 3600 true
#bash dev.sh test aixcc/jvm/bcel '*' 3600 true
#bash dev.sh test aixcc/jvm/beanutils '*' 3600 true
#bash dev.sh test aixcc/jvm/pac4j '*' 3600 true
#bash dev.sh test aixcc/jvm/cxf '*' 3600 true
#bash dev.sh test aixcc/jvm/htmlunit '*' 3600 true
#bash dev.sh test aixcc/jvm/jackson-databind '*' 1800 true
#bash dev.sh test aixcc/jvm/jakarta-mail-api '*' 3600 true
#bash dev.sh test aixcc/jvm/kylin '*' 3600 true
#bash dev.sh test aixcc/jvm/olingo '*' 3600 true
#bash dev.sh test aixcc/jvm/oripa '*' 3600 true
#bash dev.sh test aixcc/jvm/shiro '*' 3600 true
#bash dev.sh test aixcc/jvm/tika 'TikaOne' 3600 true
#bash dev.sh test aixcc/jvm/xstream '*' 3600 true
#bash dev.sh test aixcc/jvm/activemq '*' 1800 true
#bash dev.sh test aixcc/jvm/rdf4j '*' 3600 true
#bash dev.sh test aixcc/jvm/ztzip '*' 3600 true
#bash dev.sh test aixcc/jvm/ztzip '*' 600 true
#bash dev.sh test aixcc/jvm/widoco '*' 3600 true
#bash dev.sh test aixcc/jvm/apache-commons-validator 'UrlValidator2Fuzzer' 3600 true
#bash dev.sh test aixcc/jvm/apache-commons-validator-diff 'UrlValidator2Fuzzer' 3600 true
#bash dev.sh test aixcc/jvm/cron-utils '*' 3600 true
#bash dev.sh test aixcc/jvm/feign 'BodyTemplateFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/jsoup 'HtmlFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/keycloak 'ServicesUtilsFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/netty '*' 3600 true
#bash dev.sh test aixcc/jvm/snappy-java '*' 3600 true
#bash dev.sh test aixcc/jvm/spring-framework 'SpelExpressionFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/sqlite-jdbc '*' 3600 true
#bash dev.sh test aixcc/jvm/struts '*' 3600 true

#bash dev.sh test aixcc/jvm/r3-tika-delta-01 'HtmlParserFuzzer' 1800 true
#bash dev.sh test aixcc/jvm/r3-tika-delta-03 'ThreeDXMLParserFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/r3-tika-delta-04 'TikaAppRUnpackerFuzzer' 1800 true
#bash dev.sh test aixcc/jvm/r3-tika-delta-05 'TikaAppUnpackerFuzzer' 1800 true
#bash dev.sh test aixcc/jvm/r3-apache-commons-compress-delta-01 '*' 1800 false
#bash dev.sh test aixcc/jvm/r3-apache-commons-compress-delta-02 'ExpanderFuzzer' 1800 true

#bash dev.sh test aixcc/jvm/imaging 'ImagingTwo' 1800 true
#bash dev.sh test aixcc/jvm/sqlite-jdbc '*' 1800 true
#bash dev.sh test aixcc/jvm/snappy-java '*' 3600 false
#bash dev.sh test aixcc/jvm/pdfbox '*' 3600 false

#bash dev.sh test aixcc/jvm/r3-tika-delta-02 'TikaAppUntarringFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/r3-tika-delta-02 'HtmlParserFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/fuzzy '*' 1800 true

#bash dev.sh test aixcc/jvm/mock-java '*' 600 true
#bash dev.sh test aixcc/jvm/r3-tika 'TikaAppUntarringFuzzer' 3600 true
#bash dev.sh test aixcc/jvm/r3-tika 'RTFParserFuzzer' 7200 true

#bash dev.sh test aixcc/jvm/mock-java '*' 600 true
bash dev.sh test aixcc/jvm/bcel BCELOne,BCELOneFDP 7200 true
bash dev.sh test aixcc/jvm/batik BatikOne,BatikOneFDP 7200 true
bash dev.sh test aixcc/jvm/beanutils BeanUtilsOne 7200 true
bash dev.sh test aixcc/jvm/cron-utils CronUtilsOne,CronUtilsOneFDP 7200 true
bash dev.sh test aixcc/jvm/cxf CXFOne,CXFTwo,CXFThree 7200 true
bash dev.sh test aixcc/jvm/geonetwork GeonetworkOne,GeonetworkOneFDP 7200 true
bash dev.sh test aixcc/jvm/htmlunit HtmlunitOne,HtmlunitOneFDP 7200 true
bash dev.sh test aixcc/jvm/imaging ImagingOne,ImagingOneFDP,ImagingTwo,ImagingTwoFDP 7200 true
bash dev.sh test aixcc/jvm/jakarta-mail-api MailApiHarnessOne,MailApiHarnessOneFDP 7200 true
bash dev.sh test aixcc/jvm/oripa OripaOne,OripaOneFDP 7200 true
bash dev.sh test aixcc/jvm/r2-zookeeper MultiProcessTxnFuzzer 7200 true
bash dev.sh test aixcc/jvm/r3-tika RTFParserFuzzer,TextAndCSVParserFuzzer,TikaAppUnpackerFuzzer,TikaAppUntarringFuzzer,XliffParserFuzzer 7200 true
bash dev.sh test aixcc/jvm/r3-tika-delta-01 HtmlParserFuzzer 7200 true
bash dev.sh test aixcc/jvm/r3-tika-delta-03 ThreeDXMLParserFuzzer 7200 true
bash dev.sh test aixcc/jvm/r3-tika-delta-04 TikaAppRUnpackerFuzzer 7200 true
bash dev.sh test aixcc/jvm/r3-tika-delta-05 TikaAppUnpackerFuzzer 7200 true
bash dev.sh test aixcc/jvm/r3_5-jackson-databind AdaLObjectReader3Fuzzer,ObjectReader2Fuzzer 7200 true
bash dev.sh test aixcc/jvm/shiro ShiroOne 7200 true
bash dev.sh test aixcc/jvm/widoco WidocoOne 7200 true
bash dev.sh test aixcc/jvm/xstream XmlFuzzer 7200 true
bash dev.sh test aixcc/jvm/ztzip ZTZIPOne 7200 true
bash dev.sh test aixcc/jvm/feign BodyTemplateFuzzer 7200 true
bash dev.sh test aixcc/jvm/beanutils BeanUtilsOne 7200 true
bash dev.sh test aixcc/jvm/jenkins JenkinsTwo,JenkinsTwoFDP,JenkinsThree,JenkinsThreeFDP,JenkinsFour,JenkinsFive,JenkinsFiveFDP 7200 true

# reached by pure fuzzer
bash dev.sh test aixcc/jvm/fuzzy FuzzyOne,FuzzyOneFDP 7200 true
bash dev.sh test aixcc/jvm/pac4j Pac4jOne 7200 true
bash dev.sh test aixcc/jvm/r1-zookeeper DataTreeFuzzer,MessageTrackerPeekReceivedFuzzer,MultiProcessTxnFuzzer,DataTreeTxnFuzzer 7200 true
bash dev.sh test aixcc/jvm/r2-apache-commons-compress CompressorGzipFuzzer,CompressTarFuzzer,CompressZipFuzzer,ExpanderFuzzer 7200 true
bash dev.sh test aixcc/jvm/rdf4j Rdf4jOne 7200 true
bash dev.sh test aixcc/jvm/tika TikaOne 7200 true

# solved by pure fuzzer
#bash dev.sh test aixcc/jvm/activemq ActivemqOne,ActivemqOneFDP 7200 true
##bash dev.sh test aixcc/jvm/activemq-var ActivemqVariantOne,ActivemqVariantOneFDP 7200 true
#bash dev.sh test aixcc/jvm/feign BodyTemplateFuzzer 7200 true
#bash dev.sh test aixcc/jvm/jackson-databind JacksonDatabindOne,JacksonDatabindOneFDP 7200 true
#bash dev.sh test aixcc/jvm/kylin KylinOne 7200 true
#bash dev.sh test aixcc/jvm/netty ByteBufUtilFuzzer,HttpRequestDecoderFuzzer,ServerCookieDecoderFuzzer 7200 true
#bash dev.sh test aixcc/jvm/olingo OlingoOne,OlingoOneFDP 7200 true
#bash dev.sh test aixcc/jvm/r3-tika-delta-02 M3U8ParserFuzzer 7200 true
#bash dev.sh test aixcc/jvm/struts StrutsOne 7200 true
